nohup: ignoring input
INFO:root:label_path: /home/dzubke/awni_speech/data/speak_train/2020-12-29/metadata-with-url_2020-12-24.tsv
INFO:root:len of auddio_trans: 1030000
INFO:root:entering write_json for speak-train_test_2020-12-28. writing json to /home/dzubke/awni_speech/data/speak_train/2020-12-29/speak-train_test_2020-12-28.json
header:  ['id', 'text', 'lessonId', 'lineId', 'uid', 'redWords_score', 'date']
100000 examples collected
100000 examples collected
200000 examples collected
200000 examples collected
300000 examples collected
300000 examples collected
300000 examples collected
300000 examples collected
300000 examples collected
300000 examples collected
300000 examples collected
300000 examples collected
300000 examples collected
400000 examples collected
400000 examples collected
400000 examples collected
400000 examples collected
400000 examples collected
400000 examples collected
400000 examples collected
500000 examples collected
500000 examples collected
500000 examples collected
500000 examples collected
500000 examples collected
600000 examples collected
600000 examples collected
600000 examples collected
600000 examples collected
600000 examples collected
600000 examples collected
600000 examples collected
700000 examples collected
700000 examples collected
700000 examples collected
800000 examples collected
800000 examples collected
800000 examples collected
800000 examples collected
800000 examples collected
900000 examples collected
1000000 examples collected
  0%|          | 0/24 [00:00<?, ?it/s]  4%|▍         | 1/24 [14:36<5:36:08, 876.90s/it]unable to download url: An unknown error occurred, please check the server response. due to exception: unknown url type: 'An unknown error occurred, please check the server response.'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "preprocess.py", line 254, in _process_sample
    urllib.request.urlretrieve(download_url, filename=audio_path)
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/urllib/request.py", line 277, in urlretrieve
    block = fp.read(bs)
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 917, in <module>
    data_preprocessor.process_datasets()
  File "preprocess.py", line 734, in process_datasets
    self.write_json_mp(json_path)
  File "preprocess.py", line 192, in write_json_mp
    pool_fn, self.audio_trans[chunk_idx * chunk_size: (chunk_idx + 1) * chunk_size]
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/dzubke/miniconda3/envs/pyt_16/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ConnectionResetError: [Errno 104] Connection reset by peer
  4%|▍         | 1/24 [29:23<11:16:06, 1763.76s/it]
